export const primary = '#90b564'
export const primaryText = '#ffffff'
export const primaryDark = '#618537'
export const primaryDarkText = '#000000'
export const primaryLightText = '#756d6d'
export const primaryBackGround = '#ffffff'